sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 7
before_script:
install:
  - npm install
  - npm install protractor
  - npm install webdriver-manager
  - sleep 5
script:
  - webdriver-manager start
  - protractor conf.js