sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 7
install:
  - npm install
  - npm install protractor
  - npm install webdriver-manager
  - sleep 10
before_script:
  - webdriver-manager update
  - sleep 10
  - webdriver-manager start
  - sleep 10
script:
   - protractor conf.js